language: cpp

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']

script:
  - ./scripts/travis.sh

