sudo: required

branches:
  only:
    - master

notifications:
  email: false

env:
  - ARCH_TRAVIS_CONFIRM_YES=1

arch:
  packages:
    - ocaml
    - cmake
    - clang
    # for the timing in the test script
    - time
  script:
    # Replaces normal gcc and needs extra confirmation
    - yes | sudo pacman -S gcc-multilib
    - ./scripts/travis.sh

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"


