# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_core_top_0_0_1/design_1_core_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_core_top_0_0 || ORIG_REF_NAME==design_1_core_top_0_0}]

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0_1/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0}]

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_0_1/design_1_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_0 || ORIG_REF_NAME==design_1_blk_mem_gen_1_0}]

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0}]

# IP: bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1}]

# IP: bd/design_1/ip/design_1_floating_point_0_0/design_1_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_0 || ORIG_REF_NAME==design_1_floating_point_0_0}]

# IP: bd/design_1/ip/design_1_floating_point_0_1/design_1_floating_point_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_1 || ORIG_REF_NAME==design_1_floating_point_0_1}]

# IP: bd/design_1/ip/design_1_floating_point_0_2/design_1_floating_point_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_2 || ORIG_REF_NAME==design_1_floating_point_0_2}]

# IP: bd/design_1/ip/design_1_floating_point_0_3/design_1_floating_point_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_3 || ORIG_REF_NAME==design_1_floating_point_0_3}]

# IP: bd/design_1/ip/design_1_floating_point_2_0/design_1_floating_point_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_2_0 || ORIG_REF_NAME==design_1_floating_point_2_0}]

# IP: bd/design_1/ip/design_1_floating_point_4_0/design_1_floating_point_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_4_0 || ORIG_REF_NAME==design_1_floating_point_4_0}]

# IP: bd/design_1/ip/design_1_floating_point_5_0/design_1_floating_point_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_5_0 || ORIG_REF_NAME==design_1_floating_point_5_0}]

# IP: bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_1 || ORIG_REF_NAME==design_1_axi_uartlite_0_1}]

# IP: bd/design_1/ip/design_1_core_top_0_axi_periph_1/design_1_core_top_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_core_top_0_axi_periph_1 || ORIG_REF_NAME==design_1_core_top_0_axi_periph_1}]

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}]

# IP: bd/design_1/ip/design_1_system_ila_0/design_1_system_ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_system_ila_0 || ORIG_REF_NAME==design_1_system_ila_0}]

# Block Designs: bd/design_1/ip/design_1_system_ila_0/bd_0/bd_384c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_384c || ORIG_REF_NAME==bd_384c}]

# IP: bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_0/bd_384c_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_384c_ila_lib_0 || ORIG_REF_NAME==bd_384c_ila_lib_0}]

# IP: bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_1/bd_384c_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_384c_g_inst_0 || ORIG_REF_NAME==bd_384c_g_inst_0}]

# IP: bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_2/bd_384c_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_384c_slot_0_aw_0 || ORIG_REF_NAME==bd_384c_slot_0_aw_0}]

# IP: bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_3/bd_384c_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_384c_slot_0_w_0 || ORIG_REF_NAME==bd_384c_slot_0_w_0}]

# IP: bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_4/bd_384c_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_384c_slot_0_b_0 || ORIG_REF_NAME==bd_384c_slot_0_b_0}]

# IP: bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_5/bd_384c_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_384c_slot_0_ar_0 || ORIG_REF_NAME==bd_384c_slot_0_ar_0}]

# IP: bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_6/bd_384c_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_384c_slot_0_r_0 || ORIG_REF_NAME==bd_384c_slot_0_r_0}]

# XDC: bd/design_1/ip/design_1_blk_mem_gen_0_0_1/design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_blk_mem_gen_1_0_1/design_1_blk_mem_gen_1_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_floating_point_0_0/design_1_floating_point_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_floating_point_0_1/design_1_floating_point_0_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_floating_point_0_2/design_1_floating_point_0_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_floating_point_0_3/design_1_floating_point_0_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_floating_point_2_0/design_1_floating_point_2_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_floating_point_4_0/design_1_floating_point_4_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_floating_point_5_0/design_1_floating_point_5_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_1 || ORIG_REF_NAME==design_1_axi_uartlite_0_1}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_uartlite_0_1/design_1_axi_uartlite_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_1 || ORIG_REF_NAME==design_1_axi_uartlite_0_1}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_384c_ila_lib_0 || ORIG_REF_NAME==bd_384c_ila_lib_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_0/bd_384c_ila_lib_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_system_ila_0/bd_0/ip/ip_1/bd_384c_g_inst_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_system_ila_0/bd_0/bd_384c_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
