set_property SRC_FILE_INFO {cfile:/home/yamaguchi/CPU-Adelie/koara/koara.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc rfile:../../../koara.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:design_1_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/yamaguchi/CPU-Adelie/koara/koara.srcs/constrs_1/new/design_1_wrapper.xdc rfile:../../../koara.srcs/constrs_1/new/design_1_wrapper.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1_p]] 0.080000000000000002
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/core_top_0/inst/u_core_reg/reg31[0]} {design_1_i/core_top_0/inst/u_core_reg/reg31[1]} {design_1_i/core_top_0/inst/u_core_reg/reg31[2]} {design_1_i/core_top_0/inst/u_core_reg/reg31[3]} {design_1_i/core_top_0/inst/u_core_reg/reg31[4]} {design_1_i/core_top_0/inst/u_core_reg/reg31[5]} {design_1_i/core_top_0/inst/u_core_reg/reg31[6]} {design_1_i/core_top_0/inst/u_core_reg/reg31[7]} {design_1_i/core_top_0/inst/u_core_reg/reg31[8]} {design_1_i/core_top_0/inst/u_core_reg/reg31[9]} {design_1_i/core_top_0/inst/u_core_reg/reg31[10]} {design_1_i/core_top_0/inst/u_core_reg/reg31[11]} {design_1_i/core_top_0/inst/u_core_reg/reg31[12]} {design_1_i/core_top_0/inst/u_core_reg/reg31[13]} {design_1_i/core_top_0/inst/u_core_reg/reg31[14]} {design_1_i/core_top_0/inst/u_core_reg/reg31[15]} {design_1_i/core_top_0/inst/u_core_reg/reg31[16]} {design_1_i/core_top_0/inst/u_core_reg/reg31[17]} {design_1_i/core_top_0/inst/u_core_reg/reg31[18]} {design_1_i/core_top_0/inst/u_core_reg/reg31[19]} {design_1_i/core_top_0/inst/u_core_reg/reg31[20]} {design_1_i/core_top_0/inst/u_core_reg/reg31[21]} {design_1_i/core_top_0/inst/u_core_reg/reg31[22]} {design_1_i/core_top_0/inst/u_core_reg/reg31[23]} {design_1_i/core_top_0/inst/u_core_reg/reg31[24]} {design_1_i/core_top_0/inst/u_core_reg/reg31[25]} {design_1_i/core_top_0/inst/u_core_reg/reg31[26]} {design_1_i/core_top_0/inst/u_core_reg/reg31[27]} {design_1_i/core_top_0/inst/u_core_reg/reg31[28]} {design_1_i/core_top_0/inst/u_core_reg/reg31[29]} {design_1_i/core_top_0/inst/u_core_reg/reg31[30]} {design_1_i/core_top_0/inst/u_core_reg/reg31[31]}]]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list {design_1_i/core_top_0/inst/u_core_reg/reg21[0]} {design_1_i/core_top_0/inst/u_core_reg/reg21[1]} {design_1_i/core_top_0/inst/u_core_reg/reg21[2]} {design_1_i/core_top_0/inst/u_core_reg/reg21[3]} {design_1_i/core_top_0/inst/u_core_reg/reg21[4]} {design_1_i/core_top_0/inst/u_core_reg/reg21[5]} {design_1_i/core_top_0/inst/u_core_reg/reg21[6]} {design_1_i/core_top_0/inst/u_core_reg/reg21[7]} {design_1_i/core_top_0/inst/u_core_reg/reg21[8]} {design_1_i/core_top_0/inst/u_core_reg/reg21[9]} {design_1_i/core_top_0/inst/u_core_reg/reg21[10]} {design_1_i/core_top_0/inst/u_core_reg/reg21[11]} {design_1_i/core_top_0/inst/u_core_reg/reg21[12]} {design_1_i/core_top_0/inst/u_core_reg/reg21[13]} {design_1_i/core_top_0/inst/u_core_reg/reg21[14]} {design_1_i/core_top_0/inst/u_core_reg/reg21[15]} {design_1_i/core_top_0/inst/u_core_reg/reg21[16]} {design_1_i/core_top_0/inst/u_core_reg/reg21[17]} {design_1_i/core_top_0/inst/u_core_reg/reg21[18]} {design_1_i/core_top_0/inst/u_core_reg/reg21[19]} {design_1_i/core_top_0/inst/u_core_reg/reg21[20]} {design_1_i/core_top_0/inst/u_core_reg/reg21[21]} {design_1_i/core_top_0/inst/u_core_reg/reg21[22]} {design_1_i/core_top_0/inst/u_core_reg/reg21[23]} {design_1_i/core_top_0/inst/u_core_reg/reg21[24]} {design_1_i/core_top_0/inst/u_core_reg/reg21[25]} {design_1_i/core_top_0/inst/u_core_reg/reg21[26]} {design_1_i/core_top_0/inst/u_core_reg/reg21[27]} {design_1_i/core_top_0/inst/u_core_reg/reg21[28]} {design_1_i/core_top_0/inst/u_core_reg/reg21[29]} {design_1_i/core_top_0/inst/u_core_reg/reg21[30]} {design_1_i/core_top_0/inst/u_core_reg/reg21[31]}]]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list {design_1_i/core_top_0/inst/u_core_reg/reg11[0]} {design_1_i/core_top_0/inst/u_core_reg/reg11[1]} {design_1_i/core_top_0/inst/u_core_reg/reg11[2]} {design_1_i/core_top_0/inst/u_core_reg/reg11[3]} {design_1_i/core_top_0/inst/u_core_reg/reg11[4]} {design_1_i/core_top_0/inst/u_core_reg/reg11[5]} {design_1_i/core_top_0/inst/u_core_reg/reg11[6]} {design_1_i/core_top_0/inst/u_core_reg/reg11[7]} {design_1_i/core_top_0/inst/u_core_reg/reg11[8]} {design_1_i/core_top_0/inst/u_core_reg/reg11[9]} {design_1_i/core_top_0/inst/u_core_reg/reg11[10]} {design_1_i/core_top_0/inst/u_core_reg/reg11[11]} {design_1_i/core_top_0/inst/u_core_reg/reg11[12]} {design_1_i/core_top_0/inst/u_core_reg/reg11[13]} {design_1_i/core_top_0/inst/u_core_reg/reg11[14]} {design_1_i/core_top_0/inst/u_core_reg/reg11[15]} {design_1_i/core_top_0/inst/u_core_reg/reg11[16]} {design_1_i/core_top_0/inst/u_core_reg/reg11[17]} {design_1_i/core_top_0/inst/u_core_reg/reg11[18]} {design_1_i/core_top_0/inst/u_core_reg/reg11[19]} {design_1_i/core_top_0/inst/u_core_reg/reg11[20]} {design_1_i/core_top_0/inst/u_core_reg/reg11[21]} {design_1_i/core_top_0/inst/u_core_reg/reg11[22]} {design_1_i/core_top_0/inst/u_core_reg/reg11[23]} {design_1_i/core_top_0/inst/u_core_reg/reg11[24]} {design_1_i/core_top_0/inst/u_core_reg/reg11[25]} {design_1_i/core_top_0/inst/u_core_reg/reg11[26]} {design_1_i/core_top_0/inst/u_core_reg/reg11[27]} {design_1_i/core_top_0/inst/u_core_reg/reg11[28]} {design_1_i/core_top_0/inst/u_core_reg/reg11[29]} {design_1_i/core_top_0/inst/u_core_reg/reg11[30]} {design_1_i/core_top_0/inst/u_core_reg/reg11[31]}]]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe31 [get_nets [list {design_1_i/core_top_0/inst/write_status__0[0]} {design_1_i/core_top_0/inst/write_status__0[1]} {design_1_i/core_top_0/inst/write_status__0[2]} {design_1_i/core_top_0/inst/write_status__0[3]} {design_1_i/core_top_0/inst/write_status__0[4]} {design_1_i/core_top_0/inst/write_status__0[5]} {design_1_i/core_top_0/inst/write_status__0[6]}]]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe32 [get_nets [list {design_1_i/core_top_0/inst/read_status__0[0]} {design_1_i/core_top_0/inst/read_status__0[1]} {design_1_i/core_top_0/inst/read_status__0[2]} {design_1_i/core_top_0/inst/read_status__0[3]} {design_1_i/core_top_0/inst/read_status__0[4]} {design_1_i/core_top_0/inst/read_status__0[5]} {design_1_i/core_top_0/inst/read_status__0[6]}]]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0/inst/clk_out1]]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/core_top_0/inst/frs2[0]} {design_1_i/core_top_0/inst/frs2[1]} {design_1_i/core_top_0/inst/frs2[2]} {design_1_i/core_top_0/inst/frs2[3]} {design_1_i/core_top_0/inst/frs2[4]} {design_1_i/core_top_0/inst/frs2[5]} {design_1_i/core_top_0/inst/frs2[6]} {design_1_i/core_top_0/inst/frs2[7]} {design_1_i/core_top_0/inst/frs2[8]} {design_1_i/core_top_0/inst/frs2[9]} {design_1_i/core_top_0/inst/frs2[10]} {design_1_i/core_top_0/inst/frs2[11]} {design_1_i/core_top_0/inst/frs2[12]} {design_1_i/core_top_0/inst/frs2[13]} {design_1_i/core_top_0/inst/frs2[14]} {design_1_i/core_top_0/inst/frs2[15]} {design_1_i/core_top_0/inst/frs2[16]} {design_1_i/core_top_0/inst/frs2[17]} {design_1_i/core_top_0/inst/frs2[18]} {design_1_i/core_top_0/inst/frs2[19]} {design_1_i/core_top_0/inst/frs2[20]} {design_1_i/core_top_0/inst/frs2[21]} {design_1_i/core_top_0/inst/frs2[22]} {design_1_i/core_top_0/inst/frs2[23]} {design_1_i/core_top_0/inst/frs2[24]} {design_1_i/core_top_0/inst/frs2[25]} {design_1_i/core_top_0/inst/frs2[26]} {design_1_i/core_top_0/inst/frs2[27]} {design_1_i/core_top_0/inst/frs2[28]} {design_1_i/core_top_0/inst/frs2[29]} {design_1_i/core_top_0/inst/frs2[30]} {design_1_i/core_top_0/inst/frs2[31]}]]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/core_top_0/inst/imm[0]} {design_1_i/core_top_0/inst/imm[1]} {design_1_i/core_top_0/inst/imm[2]} {design_1_i/core_top_0/inst/imm[3]} {design_1_i/core_top_0/inst/imm[4]} {design_1_i/core_top_0/inst/imm[5]} {design_1_i/core_top_0/inst/imm[6]} {design_1_i/core_top_0/inst/imm[7]} {design_1_i/core_top_0/inst/imm[8]} {design_1_i/core_top_0/inst/imm[9]} {design_1_i/core_top_0/inst/imm[10]} {design_1_i/core_top_0/inst/imm[11]} {design_1_i/core_top_0/inst/imm[12]} {design_1_i/core_top_0/inst/imm[13]} {design_1_i/core_top_0/inst/imm[14]} {design_1_i/core_top_0/inst/imm[15]} {design_1_i/core_top_0/inst/imm[16]} {design_1_i/core_top_0/inst/imm[17]} {design_1_i/core_top_0/inst/imm[18]} {design_1_i/core_top_0/inst/imm[19]} {design_1_i/core_top_0/inst/imm[20]} {design_1_i/core_top_0/inst/imm[21]} {design_1_i/core_top_0/inst/imm[22]} {design_1_i/core_top_0/inst/imm[23]} {design_1_i/core_top_0/inst/imm[24]} {design_1_i/core_top_0/inst/imm[25]} {design_1_i/core_top_0/inst/imm[26]} {design_1_i/core_top_0/inst/imm[27]} {design_1_i/core_top_0/inst/imm[28]} {design_1_i/core_top_0/inst/imm[29]} {design_1_i/core_top_0/inst/imm[30]} {design_1_i/core_top_0/inst/imm[31]}]]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/core_top_0/inst/frs2_num[0]} {design_1_i/core_top_0/inst/frs2_num[1]} {design_1_i/core_top_0/inst/frs2_num[2]} {design_1_i/core_top_0/inst/frs2_num[3]} {design_1_i/core_top_0/inst/frs2_num[4]}]]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/core_top_0/inst/fwr_addr[0]} {design_1_i/core_top_0/inst/fwr_addr[1]} {design_1_i/core_top_0/inst/fwr_addr[2]} {design_1_i/core_top_0/inst/fwr_addr[3]} {design_1_i/core_top_0/inst/fwr_addr[4]}]]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/core_top_0/inst/frs1_num[0]} {design_1_i/core_top_0/inst/frs1_num[1]} {design_1_i/core_top_0/inst/frs1_num[2]} {design_1_i/core_top_0/inst/frs1_num[3]} {design_1_i/core_top_0/inst/frs1_num[4]}]]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/core_top_0_interface_aximm_WSTRB[0]}]]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/core_top_0/inst/wr_pc[0]} {design_1_i/core_top_0/inst/wr_pc[1]} {design_1_i/core_top_0/inst/wr_pc[2]} {design_1_i/core_top_0/inst/wr_pc[3]} {design_1_i/core_top_0/inst/wr_pc[4]} {design_1_i/core_top_0/inst/wr_pc[5]} {design_1_i/core_top_0/inst/wr_pc[6]} {design_1_i/core_top_0/inst/wr_pc[7]} {design_1_i/core_top_0/inst/wr_pc[8]} {design_1_i/core_top_0/inst/wr_pc[9]} {design_1_i/core_top_0/inst/wr_pc[10]} {design_1_i/core_top_0/inst/wr_pc[11]} {design_1_i/core_top_0/inst/wr_pc[12]} {design_1_i/core_top_0/inst/wr_pc[13]} {design_1_i/core_top_0/inst/wr_pc[14]} {design_1_i/core_top_0/inst/wr_pc[15]} {design_1_i/core_top_0/inst/wr_pc[16]} {design_1_i/core_top_0/inst/wr_pc[17]} {design_1_i/core_top_0/inst/wr_pc[18]} {design_1_i/core_top_0/inst/wr_pc[19]} {design_1_i/core_top_0/inst/wr_pc[20]} {design_1_i/core_top_0/inst/wr_pc[21]} {design_1_i/core_top_0/inst/wr_pc[22]} {design_1_i/core_top_0/inst/wr_pc[23]} {design_1_i/core_top_0/inst/wr_pc[24]} {design_1_i/core_top_0/inst/wr_pc[25]} {design_1_i/core_top_0/inst/wr_pc[26]} {design_1_i/core_top_0/inst/wr_pc[27]} {design_1_i/core_top_0/inst/wr_pc[28]} {design_1_i/core_top_0/inst/wr_pc[29]} {design_1_i/core_top_0/inst/wr_pc[30]} {design_1_i/core_top_0/inst/wr_pc[31]}]]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/core_top_0/inst/pc_add_imm[0]} {design_1_i/core_top_0/inst/pc_add_imm[1]} {design_1_i/core_top_0/inst/pc_add_imm[2]} {design_1_i/core_top_0/inst/pc_add_imm[3]} {design_1_i/core_top_0/inst/pc_add_imm[4]} {design_1_i/core_top_0/inst/pc_add_imm[5]} {design_1_i/core_top_0/inst/pc_add_imm[6]} {design_1_i/core_top_0/inst/pc_add_imm[7]} {design_1_i/core_top_0/inst/pc_add_imm[8]} {design_1_i/core_top_0/inst/pc_add_imm[9]} {design_1_i/core_top_0/inst/pc_add_imm[10]} {design_1_i/core_top_0/inst/pc_add_imm[11]} {design_1_i/core_top_0/inst/pc_add_imm[12]} {design_1_i/core_top_0/inst/pc_add_imm[13]} {design_1_i/core_top_0/inst/pc_add_imm[14]} {design_1_i/core_top_0/inst/pc_add_imm[15]} {design_1_i/core_top_0/inst/pc_add_imm[16]} {design_1_i/core_top_0/inst/pc_add_imm[17]} {design_1_i/core_top_0/inst/pc_add_imm[18]} {design_1_i/core_top_0/inst/pc_add_imm[19]} {design_1_i/core_top_0/inst/pc_add_imm[20]} {design_1_i/core_top_0/inst/pc_add_imm[21]} {design_1_i/core_top_0/inst/pc_add_imm[22]} {design_1_i/core_top_0/inst/pc_add_imm[23]} {design_1_i/core_top_0/inst/pc_add_imm[24]} {design_1_i/core_top_0/inst/pc_add_imm[25]} {design_1_i/core_top_0/inst/pc_add_imm[26]} {design_1_i/core_top_0/inst/pc_add_imm[27]} {design_1_i/core_top_0/inst/pc_add_imm[28]} {design_1_i/core_top_0/inst/pc_add_imm[29]} {design_1_i/core_top_0/inst/pc_add_imm[30]} {design_1_i/core_top_0/inst/pc_add_imm[31]}]]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/core_top_0/inst/rs2[0]} {design_1_i/core_top_0/inst/rs2[1]} {design_1_i/core_top_0/inst/rs2[2]} {design_1_i/core_top_0/inst/rs2[3]} {design_1_i/core_top_0/inst/rs2[4]} {design_1_i/core_top_0/inst/rs2[5]} {design_1_i/core_top_0/inst/rs2[6]} {design_1_i/core_top_0/inst/rs2[7]} {design_1_i/core_top_0/inst/rs2[8]} {design_1_i/core_top_0/inst/rs2[9]} {design_1_i/core_top_0/inst/rs2[10]} {design_1_i/core_top_0/inst/rs2[11]} {design_1_i/core_top_0/inst/rs2[12]} {design_1_i/core_top_0/inst/rs2[13]} {design_1_i/core_top_0/inst/rs2[14]} {design_1_i/core_top_0/inst/rs2[15]} {design_1_i/core_top_0/inst/rs2[16]} {design_1_i/core_top_0/inst/rs2[17]} {design_1_i/core_top_0/inst/rs2[18]} {design_1_i/core_top_0/inst/rs2[19]} {design_1_i/core_top_0/inst/rs2[20]} {design_1_i/core_top_0/inst/rs2[21]} {design_1_i/core_top_0/inst/rs2[22]} {design_1_i/core_top_0/inst/rs2[23]} {design_1_i/core_top_0/inst/rs2[24]} {design_1_i/core_top_0/inst/rs2[25]} {design_1_i/core_top_0/inst/rs2[26]} {design_1_i/core_top_0/inst/rs2[27]} {design_1_i/core_top_0/inst/rs2[28]} {design_1_i/core_top_0/inst/rs2[29]} {design_1_i/core_top_0/inst/rs2[30]} {design_1_i/core_top_0/inst/rs2[31]}]]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 7 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/core_top_0/inst/read_status[0]} {design_1_i/core_top_0/inst/read_status[1]} {design_1_i/core_top_0/inst/read_status[2]} {design_1_i/core_top_0/inst/read_status[3]} {design_1_i/core_top_0/inst/read_status[4]} {design_1_i/core_top_0/inst/read_status[5]} {design_1_i/core_top_0/inst/read_status[6]}]]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/core_top_0/inst/wr_addr[0]} {design_1_i/core_top_0/inst/wr_addr[1]} {design_1_i/core_top_0/inst/wr_addr[2]} {design_1_i/core_top_0/inst/wr_addr[3]} {design_1_i/core_top_0/inst/wr_addr[4]}]]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/core_top_0/inst/rs1_num[0]} {design_1_i/core_top_0/inst/rs1_num[1]} {design_1_i/core_top_0/inst/rs1_num[2]} {design_1_i/core_top_0/inst/rs1_num[3]} {design_1_i/core_top_0/inst/rs1_num[4]}]]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_1_i/core_top_0/inst/pc_before[0]} {design_1_i/core_top_0/inst/pc_before[1]} {design_1_i/core_top_0/inst/pc_before[2]} {design_1_i/core_top_0/inst/pc_before[3]} {design_1_i/core_top_0/inst/pc_before[4]} {design_1_i/core_top_0/inst/pc_before[5]} {design_1_i/core_top_0/inst/pc_before[6]} {design_1_i/core_top_0/inst/pc_before[7]} {design_1_i/core_top_0/inst/pc_before[8]} {design_1_i/core_top_0/inst/pc_before[9]} {design_1_i/core_top_0/inst/pc_before[10]} {design_1_i/core_top_0/inst/pc_before[11]} {design_1_i/core_top_0/inst/pc_before[12]} {design_1_i/core_top_0/inst/pc_before[13]} {design_1_i/core_top_0/inst/pc_before[14]} {design_1_i/core_top_0/inst/pc_before[15]} {design_1_i/core_top_0/inst/pc_before[16]} {design_1_i/core_top_0/inst/pc_before[17]} {design_1_i/core_top_0/inst/pc_before[18]} {design_1_i/core_top_0/inst/pc_before[19]} {design_1_i/core_top_0/inst/pc_before[20]} {design_1_i/core_top_0/inst/pc_before[21]} {design_1_i/core_top_0/inst/pc_before[22]} {design_1_i/core_top_0/inst/pc_before[23]} {design_1_i/core_top_0/inst/pc_before[24]} {design_1_i/core_top_0/inst/pc_before[25]} {design_1_i/core_top_0/inst/pc_before[26]} {design_1_i/core_top_0/inst/pc_before[27]} {design_1_i/core_top_0/inst/pc_before[28]} {design_1_i/core_top_0/inst/pc_before[29]} {design_1_i/core_top_0/inst/pc_before[30]} {design_1_i/core_top_0/inst/pc_before[31]}]]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/core_top_0/inst/pc_add_4[0]} {design_1_i/core_top_0/inst/pc_add_4[1]} {design_1_i/core_top_0/inst/pc_add_4[2]} {design_1_i/core_top_0/inst/pc_add_4[3]} {design_1_i/core_top_0/inst/pc_add_4[4]} {design_1_i/core_top_0/inst/pc_add_4[5]} {design_1_i/core_top_0/inst/pc_add_4[6]} {design_1_i/core_top_0/inst/pc_add_4[7]} {design_1_i/core_top_0/inst/pc_add_4[8]} {design_1_i/core_top_0/inst/pc_add_4[9]} {design_1_i/core_top_0/inst/pc_add_4[10]} {design_1_i/core_top_0/inst/pc_add_4[11]} {design_1_i/core_top_0/inst/pc_add_4[12]} {design_1_i/core_top_0/inst/pc_add_4[13]} {design_1_i/core_top_0/inst/pc_add_4[14]} {design_1_i/core_top_0/inst/pc_add_4[15]} {design_1_i/core_top_0/inst/pc_add_4[16]} {design_1_i/core_top_0/inst/pc_add_4[17]} {design_1_i/core_top_0/inst/pc_add_4[18]} {design_1_i/core_top_0/inst/pc_add_4[19]} {design_1_i/core_top_0/inst/pc_add_4[20]} {design_1_i/core_top_0/inst/pc_add_4[21]} {design_1_i/core_top_0/inst/pc_add_4[22]} {design_1_i/core_top_0/inst/pc_add_4[23]} {design_1_i/core_top_0/inst/pc_add_4[24]} {design_1_i/core_top_0/inst/pc_add_4[25]} {design_1_i/core_top_0/inst/pc_add_4[26]} {design_1_i/core_top_0/inst/pc_add_4[27]} {design_1_i/core_top_0/inst/pc_add_4[28]} {design_1_i/core_top_0/inst/pc_add_4[29]} {design_1_i/core_top_0/inst/pc_add_4[30]} {design_1_i/core_top_0/inst/pc_add_4[31]}]]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {design_1_i/core_top_0/inst/wr_data[0]} {design_1_i/core_top_0/inst/wr_data[1]} {design_1_i/core_top_0/inst/wr_data[2]} {design_1_i/core_top_0/inst/wr_data[3]} {design_1_i/core_top_0/inst/wr_data[4]} {design_1_i/core_top_0/inst/wr_data[5]} {design_1_i/core_top_0/inst/wr_data[6]} {design_1_i/core_top_0/inst/wr_data[7]} {design_1_i/core_top_0/inst/wr_data[8]} {design_1_i/core_top_0/inst/wr_data[9]} {design_1_i/core_top_0/inst/wr_data[10]} {design_1_i/core_top_0/inst/wr_data[11]} {design_1_i/core_top_0/inst/wr_data[12]} {design_1_i/core_top_0/inst/wr_data[13]} {design_1_i/core_top_0/inst/wr_data[14]} {design_1_i/core_top_0/inst/wr_data[15]} {design_1_i/core_top_0/inst/wr_data[16]} {design_1_i/core_top_0/inst/wr_data[17]} {design_1_i/core_top_0/inst/wr_data[18]} {design_1_i/core_top_0/inst/wr_data[19]} {design_1_i/core_top_0/inst/wr_data[20]} {design_1_i/core_top_0/inst/wr_data[21]} {design_1_i/core_top_0/inst/wr_data[22]} {design_1_i/core_top_0/inst/wr_data[23]} {design_1_i/core_top_0/inst/wr_data[24]} {design_1_i/core_top_0/inst/wr_data[25]} {design_1_i/core_top_0/inst/wr_data[26]} {design_1_i/core_top_0/inst/wr_data[27]} {design_1_i/core_top_0/inst/wr_data[28]} {design_1_i/core_top_0/inst/wr_data[29]} {design_1_i/core_top_0/inst/wr_data[30]} {design_1_i/core_top_0/inst/wr_data[31]}]]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_1_i/core_top_0/inst/rdata[0]} {design_1_i/core_top_0/inst/rdata[1]} {design_1_i/core_top_0/inst/rdata[2]} {design_1_i/core_top_0/inst/rdata[3]} {design_1_i/core_top_0/inst/rdata[4]} {design_1_i/core_top_0/inst/rdata[5]} {design_1_i/core_top_0/inst/rdata[6]} {design_1_i/core_top_0/inst/rdata[7]}]]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list {design_1_i/core_top_0/inst/pc[0]} {design_1_i/core_top_0/inst/pc[1]} {design_1_i/core_top_0/inst/pc[2]} {design_1_i/core_top_0/inst/pc[3]} {design_1_i/core_top_0/inst/pc[4]} {design_1_i/core_top_0/inst/pc[5]} {design_1_i/core_top_0/inst/pc[6]} {design_1_i/core_top_0/inst/pc[7]} {design_1_i/core_top_0/inst/pc[8]} {design_1_i/core_top_0/inst/pc[9]} {design_1_i/core_top_0/inst/pc[10]} {design_1_i/core_top_0/inst/pc[11]} {design_1_i/core_top_0/inst/pc[12]} {design_1_i/core_top_0/inst/pc[13]} {design_1_i/core_top_0/inst/pc[14]} {design_1_i/core_top_0/inst/pc[15]} {design_1_i/core_top_0/inst/pc[16]} {design_1_i/core_top_0/inst/pc[17]} {design_1_i/core_top_0/inst/pc[18]} {design_1_i/core_top_0/inst/pc[19]} {design_1_i/core_top_0/inst/pc[20]} {design_1_i/core_top_0/inst/pc[21]} {design_1_i/core_top_0/inst/pc[22]} {design_1_i/core_top_0/inst/pc[23]} {design_1_i/core_top_0/inst/pc[24]} {design_1_i/core_top_0/inst/pc[25]} {design_1_i/core_top_0/inst/pc[26]} {design_1_i/core_top_0/inst/pc[27]} {design_1_i/core_top_0/inst/pc[28]} {design_1_i/core_top_0/inst/pc[29]} {design_1_i/core_top_0/inst/pc[30]} {design_1_i/core_top_0/inst/pc[31]}]]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list {design_1_i/core_top_0/inst/rs2_num[0]} {design_1_i/core_top_0/inst/rs2_num[1]} {design_1_i/core_top_0/inst/rs2_num[2]} {design_1_i/core_top_0/inst/rs2_num[3]} {design_1_i/core_top_0/inst/rs2_num[4]}]]
set_property src_info {type:XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list {design_1_i/core_top_0/inst/rs1[0]} {design_1_i/core_top_0/inst/rs1[1]} {design_1_i/core_top_0/inst/rs1[2]} {design_1_i/core_top_0/inst/rs1[3]} {design_1_i/core_top_0/inst/rs1[4]} {design_1_i/core_top_0/inst/rs1[5]} {design_1_i/core_top_0/inst/rs1[6]} {design_1_i/core_top_0/inst/rs1[7]} {design_1_i/core_top_0/inst/rs1[8]} {design_1_i/core_top_0/inst/rs1[9]} {design_1_i/core_top_0/inst/rs1[10]} {design_1_i/core_top_0/inst/rs1[11]} {design_1_i/core_top_0/inst/rs1[12]} {design_1_i/core_top_0/inst/rs1[13]} {design_1_i/core_top_0/inst/rs1[14]} {design_1_i/core_top_0/inst/rs1[15]} {design_1_i/core_top_0/inst/rs1[16]} {design_1_i/core_top_0/inst/rs1[17]} {design_1_i/core_top_0/inst/rs1[18]} {design_1_i/core_top_0/inst/rs1[19]} {design_1_i/core_top_0/inst/rs1[20]} {design_1_i/core_top_0/inst/rs1[21]} {design_1_i/core_top_0/inst/rs1[22]} {design_1_i/core_top_0/inst/rs1[23]} {design_1_i/core_top_0/inst/rs1[24]} {design_1_i/core_top_0/inst/rs1[25]} {design_1_i/core_top_0/inst/rs1[26]} {design_1_i/core_top_0/inst/rs1[27]} {design_1_i/core_top_0/inst/rs1[28]} {design_1_i/core_top_0/inst/rs1[29]} {design_1_i/core_top_0/inst/rs1[30]} {design_1_i/core_top_0/inst/rs1[31]}]]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 7 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list {design_1_i/core_top_0/inst/write_status[0]} {design_1_i/core_top_0/inst/write_status[1]} {design_1_i/core_top_0/inst/write_status[2]} {design_1_i/core_top_0/inst/write_status[3]} {design_1_i/core_top_0/inst/write_status[4]} {design_1_i/core_top_0/inst/write_status[5]} {design_1_i/core_top_0/inst/write_status[6]}]]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list {design_1_i/core_top_0/inst/pc_jalr[0]} {design_1_i/core_top_0/inst/pc_jalr[1]} {design_1_i/core_top_0/inst/pc_jalr[2]} {design_1_i/core_top_0/inst/pc_jalr[3]} {design_1_i/core_top_0/inst/pc_jalr[4]} {design_1_i/core_top_0/inst/pc_jalr[5]} {design_1_i/core_top_0/inst/pc_jalr[6]} {design_1_i/core_top_0/inst/pc_jalr[7]} {design_1_i/core_top_0/inst/pc_jalr[8]} {design_1_i/core_top_0/inst/pc_jalr[9]} {design_1_i/core_top_0/inst/pc_jalr[10]} {design_1_i/core_top_0/inst/pc_jalr[11]} {design_1_i/core_top_0/inst/pc_jalr[12]} {design_1_i/core_top_0/inst/pc_jalr[13]} {design_1_i/core_top_0/inst/pc_jalr[14]} {design_1_i/core_top_0/inst/pc_jalr[15]} {design_1_i/core_top_0/inst/pc_jalr[16]} {design_1_i/core_top_0/inst/pc_jalr[17]} {design_1_i/core_top_0/inst/pc_jalr[18]} {design_1_i/core_top_0/inst/pc_jalr[19]} {design_1_i/core_top_0/inst/pc_jalr[20]} {design_1_i/core_top_0/inst/pc_jalr[21]} {design_1_i/core_top_0/inst/pc_jalr[22]} {design_1_i/core_top_0/inst/pc_jalr[23]} {design_1_i/core_top_0/inst/pc_jalr[24]} {design_1_i/core_top_0/inst/pc_jalr[25]} {design_1_i/core_top_0/inst/pc_jalr[26]} {design_1_i/core_top_0/inst/pc_jalr[27]} {design_1_i/core_top_0/inst/pc_jalr[28]} {design_1_i/core_top_0/inst/pc_jalr[29]} {design_1_i/core_top_0/inst/pc_jalr[30]} {design_1_i/core_top_0/inst/pc_jalr[31]}]]
set_property src_info {type:XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list {design_1_i/core_top_0/inst/frd_num[0]} {design_1_i/core_top_0/inst/frd_num[1]} {design_1_i/core_top_0/inst/frd_num[2]} {design_1_i/core_top_0/inst/frd_num[3]} {design_1_i/core_top_0/inst/frd_num[4]}]]
set_property src_info {type:XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list {design_1_i/core_top_0/inst/rd_num[0]} {design_1_i/core_top_0/inst/rd_num[1]} {design_1_i/core_top_0/inst/rd_num[2]} {design_1_i/core_top_0/inst/rd_num[3]} {design_1_i/core_top_0/inst/rd_num[4]}]]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list {design_1_i/core_top_0/inst/alu_result[0]} {design_1_i/core_top_0/inst/alu_result[1]} {design_1_i/core_top_0/inst/alu_result[2]} {design_1_i/core_top_0/inst/alu_result[3]} {design_1_i/core_top_0/inst/alu_result[4]} {design_1_i/core_top_0/inst/alu_result[5]} {design_1_i/core_top_0/inst/alu_result[6]} {design_1_i/core_top_0/inst/alu_result[7]} {design_1_i/core_top_0/inst/alu_result[8]} {design_1_i/core_top_0/inst/alu_result[9]} {design_1_i/core_top_0/inst/alu_result[10]} {design_1_i/core_top_0/inst/alu_result[11]} {design_1_i/core_top_0/inst/alu_result[12]} {design_1_i/core_top_0/inst/alu_result[13]} {design_1_i/core_top_0/inst/alu_result[14]} {design_1_i/core_top_0/inst/alu_result[15]} {design_1_i/core_top_0/inst/alu_result[16]} {design_1_i/core_top_0/inst/alu_result[17]} {design_1_i/core_top_0/inst/alu_result[18]} {design_1_i/core_top_0/inst/alu_result[19]} {design_1_i/core_top_0/inst/alu_result[20]} {design_1_i/core_top_0/inst/alu_result[21]} {design_1_i/core_top_0/inst/alu_result[22]} {design_1_i/core_top_0/inst/alu_result[23]} {design_1_i/core_top_0/inst/alu_result[24]} {design_1_i/core_top_0/inst/alu_result[25]} {design_1_i/core_top_0/inst/alu_result[26]} {design_1_i/core_top_0/inst/alu_result[27]} {design_1_i/core_top_0/inst/alu_result[28]} {design_1_i/core_top_0/inst/alu_result[29]} {design_1_i/core_top_0/inst/alu_result[30]} {design_1_i/core_top_0/inst/alu_result[31]}]]
set_property src_info {type:XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 7 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list {design_1_i/core_top_0/inst/cpu_state[0]} {design_1_i/core_top_0/inst/cpu_state[1]} {design_1_i/core_top_0/inst/cpu_state[2]} {design_1_i/core_top_0/inst/cpu_state[3]} {design_1_i/core_top_0/inst/cpu_state[4]} {design_1_i/core_top_0/inst/cpu_state[5]} {design_1_i/core_top_0/inst/cpu_state[6]}]]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list {design_1_i/core_top_0/inst/frs1[0]} {design_1_i/core_top_0/inst/frs1[1]} {design_1_i/core_top_0/inst/frs1[2]} {design_1_i/core_top_0/inst/frs1[3]} {design_1_i/core_top_0/inst/frs1[4]} {design_1_i/core_top_0/inst/frs1[5]} {design_1_i/core_top_0/inst/frs1[6]} {design_1_i/core_top_0/inst/frs1[7]} {design_1_i/core_top_0/inst/frs1[8]} {design_1_i/core_top_0/inst/frs1[9]} {design_1_i/core_top_0/inst/frs1[10]} {design_1_i/core_top_0/inst/frs1[11]} {design_1_i/core_top_0/inst/frs1[12]} {design_1_i/core_top_0/inst/frs1[13]} {design_1_i/core_top_0/inst/frs1[14]} {design_1_i/core_top_0/inst/frs1[15]} {design_1_i/core_top_0/inst/frs1[16]} {design_1_i/core_top_0/inst/frs1[17]} {design_1_i/core_top_0/inst/frs1[18]} {design_1_i/core_top_0/inst/frs1[19]} {design_1_i/core_top_0/inst/frs1[20]} {design_1_i/core_top_0/inst/frs1[21]} {design_1_i/core_top_0/inst/frs1[22]} {design_1_i/core_top_0/inst/frs1[23]} {design_1_i/core_top_0/inst/frs1[24]} {design_1_i/core_top_0/inst/frs1[25]} {design_1_i/core_top_0/inst/frs1[26]} {design_1_i/core_top_0/inst/frs1[27]} {design_1_i/core_top_0/inst/frs1[28]} {design_1_i/core_top_0/inst/frs1[29]} {design_1_i/core_top_0/inst/frs1[30]} {design_1_i/core_top_0/inst/frs1[31]}]]
set_property src_info {type:XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list design_1_i/core_top_0/inst/addsub_f]]
set_property src_info {type:XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list design_1_i/core_top_0/inst/comp_f]]
set_property src_info {type:XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list design_1_i/core_top_0/inst/div_f]]
set_property src_info {type:XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe29 [get_nets [list design_1_i/core_top_0/inst/fcvtsw_f]]
set_property src_info {type:XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe30 [get_nets [list design_1_i/core_top_0/inst/fcvtws_f]]
set_property src_info {type:XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe31 [get_nets [list design_1_i/core_top_0/inst/fsqrts_f]]
set_property src_info {type:XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property src_info {type:XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
set_property src_info {type:XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe32 [get_nets [list design_1_i/core_top_0/inst/i_add]]
set_property src_info {type:XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property src_info {type:XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
set_property src_info {type:XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe33 [get_nets [list design_1_i/core_top_0/inst/i_addi]]
set_property src_info {type:XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property src_info {type:XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
set_property src_info {type:XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe34 [get_nets [list design_1_i/core_top_0/inst/i_and]]
set_property src_info {type:XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property src_info {type:XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
set_property src_info {type:XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe35 [get_nets [list design_1_i/core_top_0/inst/i_andi]]
set_property src_info {type:XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property src_info {type:XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
set_property src_info {type:XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe36 [get_nets [list design_1_i/core_top_0/inst/i_auipc]]
set_property src_info {type:XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property src_info {type:XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
set_property src_info {type:XDC file:2 line:168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe37 [get_nets [list design_1_i/core_top_0/inst/i_beq]]
set_property src_info {type:XDC file:2 line:169 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe38 [get_nets [list design_1_i/core_top_0/inst/i_bge]]
set_property src_info {type:XDC file:2 line:173 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe39 [get_nets [list design_1_i/core_top_0/inst/i_bgeu]]
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe40 [get_nets [list design_1_i/core_top_0/inst/i_blt]]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe41 [get_nets [list design_1_i/core_top_0/inst/i_bltu]]
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe42 [get_nets [list design_1_i/core_top_0/inst/i_bne]]
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe43 [get_nets [list design_1_i/core_top_0/inst/i_fadds]]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe44 [get_nets [list design_1_i/core_top_0/inst/i_fcvtsw]]
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe45]
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe45 [get_nets [list design_1_i/core_top_0/inst/i_fcvtws]]
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe46]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe46 [get_nets [list design_1_i/core_top_0/inst/i_fdivs]]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe47]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe47 [get_nets [list design_1_i/core_top_0/inst/i_feqs]]
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe48]
set_property src_info {type:XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe48]
set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe48 [get_nets [list design_1_i/core_top_0/inst/i_fles]]
set_property src_info {type:XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe49]
set_property src_info {type:XDC file:2 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe49]
set_property src_info {type:XDC file:2 line:216 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe49 [get_nets [list design_1_i/core_top_0/inst/i_flts]]
set_property src_info {type:XDC file:2 line:217 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe50]
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe50]
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe50 [get_nets [list design_1_i/core_top_0/inst/i_flw]]
set_property src_info {type:XDC file:2 line:221 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe51]
set_property src_info {type:XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe51]
set_property src_info {type:XDC file:2 line:224 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe51 [get_nets [list design_1_i/core_top_0/inst/i_fmuls]]
set_property src_info {type:XDC file:2 line:225 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe52]
set_property src_info {type:XDC file:2 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe52]
set_property src_info {type:XDC file:2 line:228 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe52 [get_nets [list design_1_i/core_top_0/inst/i_fmvsx]]
set_property src_info {type:XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe53]
set_property src_info {type:XDC file:2 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe53]
set_property src_info {type:XDC file:2 line:232 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe53 [get_nets [list design_1_i/core_top_0/inst/i_fsgnjxs]]
set_property src_info {type:XDC file:2 line:233 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe54]
set_property src_info {type:XDC file:2 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe54]
set_property src_info {type:XDC file:2 line:236 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe54 [get_nets [list design_1_i/core_top_0/inst/i_fsqrts]]
set_property src_info {type:XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe55]
set_property src_info {type:XDC file:2 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe55]
set_property src_info {type:XDC file:2 line:240 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe55 [get_nets [list design_1_i/core_top_0/inst/i_fsubs]]
set_property src_info {type:XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe56]
set_property src_info {type:XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe56]
set_property src_info {type:XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe56 [get_nets [list design_1_i/core_top_0/inst/i_fsw]]
set_property src_info {type:XDC file:2 line:245 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe57]
set_property src_info {type:XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe57]
set_property src_info {type:XDC file:2 line:248 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe57 [get_nets [list design_1_i/core_top_0/inst/i_in]]
set_property src_info {type:XDC file:2 line:249 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe58]
set_property src_info {type:XDC file:2 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe58]
set_property src_info {type:XDC file:2 line:252 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe58 [get_nets [list design_1_i/core_top_0/inst/i_jal]]
set_property src_info {type:XDC file:2 line:253 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe59]
set_property src_info {type:XDC file:2 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe59]
set_property src_info {type:XDC file:2 line:256 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe59 [get_nets [list design_1_i/core_top_0/inst/i_jalr]]
set_property src_info {type:XDC file:2 line:257 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe60]
set_property src_info {type:XDC file:2 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe60]
set_property src_info {type:XDC file:2 line:260 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe60 [get_nets [list design_1_i/core_top_0/inst/i_lb]]
set_property src_info {type:XDC file:2 line:261 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe61]
set_property src_info {type:XDC file:2 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe61]
set_property src_info {type:XDC file:2 line:264 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe61 [get_nets [list design_1_i/core_top_0/inst/i_lbu]]
set_property src_info {type:XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe62]
set_property src_info {type:XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe62]
set_property src_info {type:XDC file:2 line:268 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe62 [get_nets [list design_1_i/core_top_0/inst/i_lh]]
set_property src_info {type:XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe63]
set_property src_info {type:XDC file:2 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe63]
set_property src_info {type:XDC file:2 line:272 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe63 [get_nets [list design_1_i/core_top_0/inst/i_lhu]]
set_property src_info {type:XDC file:2 line:273 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe64]
set_property src_info {type:XDC file:2 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe64]
set_property src_info {type:XDC file:2 line:276 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe64 [get_nets [list design_1_i/core_top_0/inst/i_lui]]
set_property src_info {type:XDC file:2 line:277 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe65]
set_property src_info {type:XDC file:2 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe65]
set_property src_info {type:XDC file:2 line:280 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe65 [get_nets [list design_1_i/core_top_0/inst/i_lw]]
set_property src_info {type:XDC file:2 line:281 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe66]
set_property src_info {type:XDC file:2 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe66]
set_property src_info {type:XDC file:2 line:284 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe66 [get_nets [list design_1_i/core_top_0/inst/i_or]]
set_property src_info {type:XDC file:2 line:285 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe67]
set_property src_info {type:XDC file:2 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe67]
set_property src_info {type:XDC file:2 line:288 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe67 [get_nets [list design_1_i/core_top_0/inst/i_ori]]
set_property src_info {type:XDC file:2 line:289 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe68]
set_property src_info {type:XDC file:2 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe68]
set_property src_info {type:XDC file:2 line:292 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe68 [get_nets [list design_1_i/core_top_0/inst/i_out]]
set_property src_info {type:XDC file:2 line:293 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe69]
set_property src_info {type:XDC file:2 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe69]
set_property src_info {type:XDC file:2 line:296 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe69 [get_nets [list design_1_i/core_top_0/inst/i_rot]]
set_property src_info {type:XDC file:2 line:297 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe70]
set_property src_info {type:XDC file:2 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe70]
set_property src_info {type:XDC file:2 line:300 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe70 [get_nets [list design_1_i/core_top_0/inst/i_sb]]
set_property src_info {type:XDC file:2 line:301 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe71]
set_property src_info {type:XDC file:2 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe71]
set_property src_info {type:XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe71 [get_nets [list design_1_i/core_top_0/inst/i_sh]]
set_property src_info {type:XDC file:2 line:305 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe72]
set_property src_info {type:XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe72]
set_property src_info {type:XDC file:2 line:308 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe72 [get_nets [list design_1_i/core_top_0/inst/i_sll]]
set_property src_info {type:XDC file:2 line:309 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe73]
set_property src_info {type:XDC file:2 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe73]
set_property src_info {type:XDC file:2 line:312 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe73 [get_nets [list design_1_i/core_top_0/inst/i_slli]]
set_property src_info {type:XDC file:2 line:313 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe74]
set_property src_info {type:XDC file:2 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe74]
set_property src_info {type:XDC file:2 line:316 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe74 [get_nets [list design_1_i/core_top_0/inst/i_slt]]
set_property src_info {type:XDC file:2 line:317 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe75]
set_property src_info {type:XDC file:2 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe75]
set_property src_info {type:XDC file:2 line:320 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe75 [get_nets [list design_1_i/core_top_0/inst/i_slti]]
set_property src_info {type:XDC file:2 line:321 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe76]
set_property src_info {type:XDC file:2 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe76]
set_property src_info {type:XDC file:2 line:324 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe76 [get_nets [list design_1_i/core_top_0/inst/i_sltiu]]
set_property src_info {type:XDC file:2 line:325 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe77]
set_property src_info {type:XDC file:2 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe77]
set_property src_info {type:XDC file:2 line:328 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe77 [get_nets [list design_1_i/core_top_0/inst/i_sltu]]
set_property src_info {type:XDC file:2 line:329 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe78]
set_property src_info {type:XDC file:2 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe78]
set_property src_info {type:XDC file:2 line:332 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe78 [get_nets [list design_1_i/core_top_0/inst/i_sra]]
set_property src_info {type:XDC file:2 line:333 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe79]
set_property src_info {type:XDC file:2 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe79]
set_property src_info {type:XDC file:2 line:336 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe79 [get_nets [list design_1_i/core_top_0/inst/i_srai]]
set_property src_info {type:XDC file:2 line:337 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe80]
set_property src_info {type:XDC file:2 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe80]
set_property src_info {type:XDC file:2 line:340 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe80 [get_nets [list design_1_i/core_top_0/inst/i_srl]]
set_property src_info {type:XDC file:2 line:341 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe81]
set_property src_info {type:XDC file:2 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe81]
set_property src_info {type:XDC file:2 line:344 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe81 [get_nets [list design_1_i/core_top_0/inst/i_srli]]
set_property src_info {type:XDC file:2 line:345 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe82]
set_property src_info {type:XDC file:2 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe82]
set_property src_info {type:XDC file:2 line:348 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe82 [get_nets [list design_1_i/core_top_0/inst/i_sub]]
set_property src_info {type:XDC file:2 line:349 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe83]
set_property src_info {type:XDC file:2 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe83]
set_property src_info {type:XDC file:2 line:352 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe83 [get_nets [list design_1_i/core_top_0/inst/i_sw]]
set_property src_info {type:XDC file:2 line:353 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe84]
set_property src_info {type:XDC file:2 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe84]
set_property src_info {type:XDC file:2 line:356 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe84 [get_nets [list design_1_i/core_top_0/inst/i_xor]]
set_property src_info {type:XDC file:2 line:357 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe85]
set_property src_info {type:XDC file:2 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe85]
set_property src_info {type:XDC file:2 line:360 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe85 [get_nets [list design_1_i/core_top_0/inst/i_xori]]
set_property src_info {type:XDC file:2 line:361 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe86]
set_property src_info {type:XDC file:2 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe86]
set_property src_info {type:XDC file:2 line:364 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe86 [get_nets [list design_1_i/core_top_0/inst/ine]]
set_property src_info {type:XDC file:2 line:365 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe87]
set_property src_info {type:XDC file:2 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe87]
set_property src_info {type:XDC file:2 line:368 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe87 [get_nets [list design_1_i/core_top_0/inst/mul_f]]
set_property src_info {type:XDC file:2 line:369 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe88]
set_property src_info {type:XDC file:2 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe88]
set_property src_info {type:XDC file:2 line:372 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe88 [get_nets [list design_1_i/core_top_0/inst/stole]]
set_property src_info {type:XDC file:2 line:373 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe89]
set_property src_info {type:XDC file:2 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe89]
set_property src_info {type:XDC file:2 line:376 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe89 [get_nets [list design_1_i/core_top_0/inst/tvalid_once]]
set_property src_info {type:XDC file:2 line:377 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe90]
set_property src_info {type:XDC file:2 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe90]
set_property src_info {type:XDC file:2 line:380 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe90 [get_nets [list design_1_i/core_top_0/inst/wr_pc_we]]
set_property src_info {type:XDC file:2 line:381 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe91]
set_property src_info {type:XDC file:2 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe91]
set_property src_info {type:XDC file:2 line:384 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe91 [get_nets [list design_1_i/core_top_0/inst/wr_we]]
set_property src_info {type:XDC file:2 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:388 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
